//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS400ImportData
    {
        public int ID { get; set; }
        public Nullable<int> Code { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> MaterialHeightLeaf { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantitySecondary { get; set; }
    }
}
