//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Downtimes
    {
        public int ID { get; set; }
        public Nullable<int> WorksID { get; set; }
        public Nullable<byte> MachineID { get; set; }
        public Nullable<byte> MachineAlarmID { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<int> Worker { get; set; }
    
        public virtual MachineAlarms MachineAlarms { get; set; }
        public virtual Machines Machines { get; set; }
        public virtual Works Works { get; set; }
    }
}
