//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineStatus
    {
        public int MachineID { get; set; }
        public string ProductCode { get; set; }
        public int MachineStateID { get; set; }
        public int Speed { get; set; }
        public int AverageSpeed { get; set; }
        public int Counter { get; set; }
        public int ResettableCounter { get; set; }
        public string ErrorString { get; set; }
    }
}
