//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineStatus
    {
        public byte MachineID { get; set; }
        public Nullable<int> WorkID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<byte> MachineStateID { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> AverageSpeed { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<int> ResettableCounter { get; set; }
        public string ErrorsString { get; set; }
        public Nullable<System.DateTime> StartPhase { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Machines Machines { get; set; }
        public virtual MachineStates MachineStates { get; set; }
    }
}
