//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessingSteps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessingSteps()
        {
            this.Works = new HashSet<Works>();
        }
    
        public int ID { get; set; }
        public Nullable<byte> MachineID { get; set; }
        public Nullable<byte> PhaseNumber { get; set; }
        public Nullable<byte> MachineStateID { get; set; }
    
        public virtual Machines Machines { get; set; }
        public virtual MachineStates MachineStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Works> Works { get; set; }
    }
}
