//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int ID { get; set; }
        public Nullable<byte> MachinesID { get; set; }
        public Nullable<int> WorkID { get; set; }
        public Nullable<System.DateTime> DateTimeProduction { get; set; }
        public Nullable<int> Items { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<byte> MachineStateID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<System.DateTime> DateProduction { get; set; }
    
        public virtual Machines Machines { get; set; }
        public virtual MachineStates MachineStates { get; set; }
        public virtual Shifts Shifts { get; set; }
        public virtual Works Works { get; set; }
    }
}
