//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ExportWorks2
    {
        public string Macchina { get; set; }
        public Nullable<int> Cod_Lavoratore { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Bolla { get; set; }
        public string Materiale { get; set; }
        public string sk { get; set; }
        public string colori { get; set; }
        public string HF { get; set; }
        public Nullable<decimal> MT_Richiesti { get; set; }
        public Nullable<decimal> MT_Fatti { get; set; }
        public Nullable<decimal> KG_Richiesti { get; set; }
        public Nullable<decimal> Kg_Fatti { get; set; }
        public string Fase { get; set; }
        public Nullable<System.DateTime> Inizio { get; set; }
        public Nullable<System.DateTime> Fine { get; set; }
        public Nullable<int> TempoMinuti { get; set; }
        public Nullable<decimal> ScartoKg { get; set; }
        public Nullable<decimal> ScartoMT { get; set; }
        public string NomeFermo { get; set; }
        public Nullable<int> Minuti { get; set; }
    }
}
