//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVCore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Works()
        {
            this.Downtimes = new HashSet<Downtimes>();
            this.Production = new HashSet<Production>();
            this.SetUpPartsLog = new HashSet<SetUpPartsLog>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> WorkStateID { get; set; }
        public Nullable<byte> MachineID { get; set; }
        public Nullable<byte> MachineStateIDProcessingStep { get; set; }
        public Nullable<int> ProcessingStepID { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityMade { get; set; }
        public string UnitOfMeasureSecondary { get; set; }
        public Nullable<decimal> QuantitySecondary { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<decimal> Waste { get; set; }
        public Nullable<decimal> Multipler { get; set; }
        public Nullable<int> Worker { get; set; }
        public Nullable<int> Worker2 { get; set; }
        public Nullable<int> Worker3 { get; set; }
        public Nullable<int> Mechanic { get; set; }
        public Nullable<int> Mechanic2 { get; set; }
        public Nullable<int> Mechanic3 { get; set; }
        public string Workers { get; set; }
        public Nullable<int> Counter { get; set; }
        public bool IsUrgent { get; set; }
        public Nullable<decimal> MaterialHeightLeaf { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> MaterialHeightLeaf2 { get; set; }
        public Nullable<decimal> Multipler2 { get; set; }
        public Nullable<decimal> RealWeightProduction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Downtimes> Downtimes { get; set; }
        public virtual Machines Machines { get; set; }
        public virtual ProcessingSteps ProcessingSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetUpPartsLog> SetUpPartsLog { get; set; }
        public virtual WorkStates WorkStates { get; set; }
    }
}
